### ISSUE TITLE
CSS hover property persists for last clicked index if pagination controls contains an ellipsis

### ISSUE THREAD

**Issue by dropfish** [michaelbromley/angularUtils#153] opened 2015-05-01 18:43 UTC
This only occurs when the pagination controls contain an ellipsis. Clicking a page number that will move the ellipsis to a different spot in the array causes the page number at the clicked index to have the CSS class associated with a mouse hover, even on mouse exit. The class disappears when you click anywhere else.

Steps to reproduce:
1) Open the [Plunker](http://plnkr.co/edit/Wtkv71LIqUR4OhzhgpqL?p=preview) example.
2) Click page 6.
3) Notice that page 7, which is where your mouse currently is, will stay darkened even when your mouse leaves the element.
4) Click anywhere else; the class that darkens that element will be removed.

Thanks!

**Comment by michaelbromley** [comment] 2015-05-10 13:47
Hi,

I can confirm I was able to reproduce this. Not got time to dig deep into it right now. The same was reported a while back: https://github.com/michaelbromley/angularUtils/issues/65, at the time I could not figure it out. 

As with any bug, it will yield with enough time put into it, but unfortunately I've not got the luxury right now. Any investigation you can do would be appreciated.

**Comment by michaelbromley** [comment] 2015-08-11 13:12
I think I figured this out as being caused by `track by $index` in the template. As soon as I get some time I'll verify and make a fix for this.

**Closed** 2015-08-27 07:38 UTC
Labels: bug
