### ISSUE TITLE
dirPaginate: ng-repeat after dir-paginate-end doesn't work

### ISSUE THREAD

**Issue by aishasims** [michaelbromley/angularUtils#92] opened 2014-12-10 22:37 UTC
Hi Michael!

When I have a ng-repeat used after my dir-paginate-end, the ng-repeat does not work.  Here's code snippet
![screen shot 2014-12-10 at 2 43 06 pm](https://cloud.githubusercontent.com/assets/3753421/5385830/e4c69ae2-807a-11e4-89ab-a4807b379fee.png)

```HTML
<tr
               dir-paginate-start="request in filtered_data = (payments | orderBy:dataParams.sort:dataParams.sortReverse | filter:{status.id:status_filter.id} | filter:refine.query) | itemsPerPage: resultsPerPage"
               current-page="pagination.currentPage"
               total-items="totalRecords">
               <td></td>
          </tr>
          <!-- payment detail -->
          <tr dir-paginate-end class="payment_detail_inline" ng-class="{show_detail:(activePayment.id && (activePayment.id == request.id))}" >
               <td>&nbsp;</td>
               <td colspan="6">
                             <div ng-repeat="item in activePayment.payment.transactions" class="fractional_row payment_transaction">
                                   <div class="three_fourths columns">{{item.label}}</div>
                                   <div class="one_fourth columns">{{item.amount}}</div>
                              </div>

               </td>
          </tr>
```

**Comment by alex-dolbik** [comment] 2015-01-21 09:24
Hi, Michael! 

Have you a solution for the problem *Kinups at 18 Dec 2014*?
Or could you share an example of a function dirPaginationLinkFn? 

Thanks!

**Comment by zacaj** [comment] 2015-01-21 19:22
Hi, I'm also having this problem, and lines 67 and 65 no longer contain any $compile call

**Comment by michaelbromley** [comment] 2015-01-22 09:16
@zacaj yeah there have been some changes since I wrote that solution. The $compile call is now on [line 84](https://github.com/michaelbromley/angularUtils/blob/master/src/directives/pagination/dirPagination.js#L84).

I'm gonna have another crack at finding a proper solution to this...

**Comment by michaelbromley** [comment] 2015-01-22 12:47
Okay, after a few more hours poking around in the belly of angular.js, I've come up with what may be a permanent fix for this issue.

The unit tests all pass, but since it is (in my opinion) rather hacky and un-elegant, I would like you guys who have this issue to try it out first, if possible, to see if it works in your real-world use cases.

Here is the updated code: https://gist.github.com/michaelbromley/ec0f433fecf23ba20528

Any advice on a better way to handle this would be appreciated. Otherwise, it'll probably suffice.

**Comment by zacaj** [comment] 2015-01-22 14:48
I've got an issue with the new version: the repeated variable from the -start directive isn't available inside ng-repeats in the -end directive.  

Example: http://plnkr.co/edit/2a5idjsgbUvyiOoFrqN6

A bit of a weird case, but it works with regular ng-repeat-start/end

**Comment by michaelbromley** [comment] 2015-03-09 09:36
@zacaj Hi, sorry for the late reply. Thanks for the feedback - I'm not going to merge my solution since it's not working properly - your use case is probably not that uncommon. I plan to give it another go probably later this week, and see if I can find a real fix for this.

**Comment by diosney** [comment] 2015-03-17 21:01
Just wanting to say that I'm having issue too. Had me looping aroung for hours searching for the root of the issue.

@michaelbromley Any fixes yet? (thanks for the directive BTW)

**Comment by diosney** [comment] 2015-03-18 15:03
@michaelbromley This is really a stopblocking for me :( 

I will dig into the comments and dive into the code to see if I can add my two cents, even with the very low possibility I have to fix it, after all you have tried several times and who better than you to do it.

Maybe you can give me some pointers in the right direction besides the comments you already had done in the related issues?

**Comment by diosney** [comment] 2015-03-18 22:51
@michaelbromley I found out that in the compile function, `tElement` has all the elements that goes from **-start** to **-end**, but in the linking function `element` only has the first **-start** element, so when ` var compiled =  $compile(element, false, 5000);` it is really compiling only the **-start** element, but not others in the range.

Maybe this throws a new light on the issue? Maybe there is a way to catch the other elements and correctly pass them to `$compile()`?

**Comment by michaelbromley** [comment] 2015-03-19 06:16
@diosney Hi, thanks for taking some time to look into this. I've been super busy this week but I really hope to get a few solid hours in tomorrow to try to solve this.

Your last comment is about as far as I have got with it - I've not come up with a way to solve that issue without breaking other use-cases (this directive gets so much use that the test suite has grown  pretty large and there are lots of specific cases that still need to work with any fix we come up with for this issue).

My ideas now are to look into the using the pre-link function or even the controller to do some of the work that is currently done between the compile & (post) link functions, as the key thing here is the order of execution, and intercepting and re-compiling the element at the right moment in the bootstrap sequence.

It may also be the case that the whole process needs a radical re-think, because my last attempt at a solution (above) had me wandering off in to a jungle of ugly hacks.

**Comment by michaelbromley** [comment] 2015-03-19 15:35
Okay, I *think* I've got some good news here.

Just spent a couple of hours again hacking away at this issue. I really isolated the problem to be the fact that, in multi-element mode, the "head" element ( the one with the `dir-paginate-start` directive attached to it) would prevent all nested directives from being compiled because it has `terminal: true`. This meant that, when we manually compile it later, the nested ng-repeat will then compile correctly.

However, the other elements in the **range** (ie the elements between the `-start` and -`end` inclusive)  had no way of similarly preventing nested directives from getting compiled. Hence the nested ng-repeat working in the "head" element but not in any of the others.

The work around I came up with is to use a "helper" directive that gets dynamically added to every element in the range. This helper simply prevents further compilation from taking place, since it is defined like so:

```JavaScript
function noCompileDirective() {
    return {
        priority: 5000,
        terminal: true
    };
}
```

Then, during the link phase, we dynamically remove these, and then manually compile *all* elements in the range when we are ready.

Please try it out and let me know if it works as expected: https://gist.github.com/michaelbromley/41eb93903120d2e3f934

I also did a lot of refactoring and if all seems well with this issue, it'll be a very nice update to the module!

**Comment by diosney** [comment] 2015-03-20 16:07
@michaelbromley Good!!! Nicely done!!! Thanks!!!

I will test the update and let you know if it works for me, since I use the directive in a lot of places and ways by now.

The following is only to let you now of my ondoings on this :smile: 

I'm pretty new to Angular that's why despite the fact that I've spent several days in full trying to fix this I had not come yet to any solution. However, I'm very confident and understandable on how the directives work by now.

I tried a lot of things but none of them worked as expected and came to think that a radical view has to be used here. 

With that in mind I'm trying to decouple the dynamic `ng-repeat` into working in conjuntion with the `dir-paginate` directive, and I think I'm halfway to make it work since it works smoothly with simple `ng-repeat`s but not with multielement `ng-repeat`s.

I will continue to work on this even if the update works since it may be good to decouple them.

**Comment by michaelbromley** [comment] 2015-03-20 16:42
Hi,

Sounds good - I'd be interested to see what you come up with.

**Comment by diosney** [comment] 2015-03-20 16:50
Nicelly done! I tested the update and it work nice for me for each use case :smile: and I used it a lot, just see:

- In a non-AJAX fashion,
- In an AJAX fashion,
- Nested dir-paginate directives,
- Dynamic pagination-id (which are giving me some troubles now but I think is not the update)
- And the list goes on but those are the most important ones.

So, thank you for your last try :) it seems was bullseye.

Now, on the "ng-repeat extract" variant, I will continue to see if it works, but I would want to know your thoughts about it since it will disrupt the current API (dir-paginate won't be a `multiElement` and maybe the current compilation of the `pagination-id` into the `itemsPerPage` may not be done).

Thanks again for your time.

**Comment by michaelbromley** [comment] 2015-03-20 18:17
Great, thanks for that. I'll commit this change then and push out a new version!

Regarding the new method you are working on - if it makes changes to the API it is unlikely that I'd want to merge it into this repo - but I'd have to see exactly how it changes things first. Additionally I'm just interested to see how else this problem can be solved, and what benefits another approach might bring.

**Closed** 2015-03-20 18:43 UTC
Labels: bug

**Comment by diosney** [comment] 2015-03-20 22:08
I've some good news on my side too, I was able to adapt the directive code to work in conjunction with `ng-repeat` instead of dynamically delegating to it. That way I think the missbehavior will be less since it avoid the compile/linking juggling.

There remains some issues though: none of the tests pass due some facts I found:

- several of them because `dirPaginate` isn't a multiElement anymore, which I think is a good thing

- a lot of them due the way they are expecting `dirPaginate` to have the repeater condition, which `ngRepeat` holds now

- `dirPaginate` is not able yet (I have to spend more time on this to find a workaroung) to dynamically set the `itemsPerPage` filter pagination id.

But I manually test several use cases of that "broken tests" and they worked smoothly.

Now, I know those are heavy points you may argue against this variant, but despite the fact that it changes the API (hence the broken tests), I may suggest to analyze it for a tentative breaking 1.0.0 version, since it do the things in a less hacky way, which in turn may lead to less missbehavior in the future.

I will set a page with several examples to send them to you if you in case you want to check them.

This is an example of how one will use it along with `ng-repeat`:

```js
<dir-pagination-controls pagination-id="some_pagination_id">"></dir-pagination-controls>

<table class="table">
	<tr dir-paginate ng-repeat-start="item in items | itemsPerPage:2:some_pagination_id">
		<td>{{ item }}</td>
		<td>
			<div ng-repeat="colour in colors">{{ colour }}</div>
		</td>
	</tr>

	<tr ng-repeat-end>
		<td>|-</td>
		<td>
			<div ng-repeat="size in sizes">{{ size }}</div>
		</td>
	</tr>
</table>

(That example works like a charm with my rearrange)

**Comment by michaelbromley** [comment] 2015-03-21 18:51
I agree that separating the pagination and ngRepeat directives would likely improve the stability of the code, since most of the complexity comes from the delegation stuff, as you mention.

My main issue with the idea of going with such a huge breaking change to the API is that lots of people already rely on this, and to change it for a 1.0 release would mean that they are unable to upgrade without re-writing all their views that use it. For those that don't want to make the upgrade, they would then miss out on future development of the 1.0 branch.

If I were starting out again from scratch, perhaps I would go with your approach (if I could have figured it out). But with things as they are, I'd say there needs to be some demonstrable benefit to justify changing the API. Perhaps there are - stability for one and maybe performance in certain cases? 

Sure - I'd be interested to see working examples as well as the code. If I don't decide to merge your changes, then it sounds like it'd still be a very worthwhile fork that could stand on its own, and people could choose which one they think fits best for their projects.

**Comment by diosney** [comment] 2015-03-22 14:57
Nice to hear your thoughts on this.
I understand you and I think it is a though decision to make.

On the versioning thing, I think that [semantic versioning](http://semver.org/) covers the incompatible x.0.0 changes, that's why a major number is incremented after all so is makes perfect sense to do it that way, so the people that wants to stick with 0.x.0 branch can do it and if they use bower, for instance, it will be very easy for them to keep track of that branch automatically.

On the demostrable benefit, this thread is just one of them, after all it remained opened for a very long time, due the complexities of the code besides the fact that most people are very accustomed to use `ng-repeat` so code is more readable too.

I really don't want to fork the project for several reasons (it will fragment the community, and since you are the original author it will be good to have all variants in the same repo endpoint, among others) so I will just silence myself on this :smile: after all, the code with the fix is working ok for now.

The changes are very simple, I just moved the whole functionality from the compile step to the link one, and obtained the repeated expression from `ng-repeat` instead. I will publish a gist in minutes. That code is not final one since it remains severeal things to be added/fixed, but demostrates how it can be used along with `ng-repeat`.

Thanks agains for the fix :smile: 

pd. Right now I'm very accustomed to your code and the directive, so any help you may need just mention me.

**Comment by diosney** [comment] 2015-03-22 15:05
Here is the gist: https://gist.github.com/diosney/da75cb845f2b7363bddb

**Comment by michaelbromley** [comment] 2015-03-23 19:19
Cheers. Re semver, I was aware of this but I would like to avoid having to maintain 2 branches (0.x & 1.x) - just keeping up with this one in my spare time is already work enough!

Thanks also for your continued input and ideas. I'm going to leave this here and think it over for next time I find myself having to fix a bunch of bugs on this. I'll ping you if I need any help.

**Comment by pacificeyes** [comment] 2015-11-06 05:22
Hi Mike,
I was too lazy to read the entire thread.
I have a very similar issue where I need to use pagination. I have the scenario of parent/child records and I want to provide expand/collapse feature. 
On parent records table I need pagination so I have used dirpaginate and on the child record I want to use ngrepeat only. However it's not working for me. So is there any permanent solution on using ngrepeat inside dirpaginate?

**Comment by michaelbromley** [comment] 2015-11-06 08:34
@pacificeyes Hi. The original issue was actually fixed with a patch ([see this comment above](https://github.com/michaelbromley/angularUtils/issues/92#ref-commit-2eaf17a). If you are still running into some problems, then I suggest you open a new issue and post some code. If you want to be very helpful (and increase the probability of me being able to fix it quickly ;) ) then see if you can reproduce the issue in a plunker demo (you can use [this](http://plnkr.co/edit/Wtkv71LIqUR4OhzhgpqL?p=preview) as a start).

**Comment by pacificeyes** [comment] 2015-11-08 05:00
Hi @michaelbromley,
I've updated the plukr shared by you.
I'm unable to populate the contact information using the ngrepeat after dir pagination. I'm using ngRepeat inside expand collapse feature. Your help on this issues will really be appreciated.

**Comment by michaelbromley** [comment] 2015-11-13 08:07
@pacificeyes when you update my plunker, it creates a new URL for your fork. You'd need to let me know what that URL is. I'm very busy this week and until mid next week, hence the slow response. I'll try to take a look if you can post the updated plunk though.

**Comment by pacificeyes** [comment] 2015-11-21 12:28
@michaelbromley,
Nevermind. My issue is resolved.
It was my bad. I was trying to use ng-repeat on the object rather than an array :(

**Comment by baldozoran** [comment] 2022-02-08 11:28
I found this very practical and good solution.
Without having to fix Angular and its compilation.
we continue to use the `ng-repeat-start` and `ng-repeat-end` and bring out our `dir-paginate` in the html page.
This will fix the problem and pagination Works!

```
<dir-pagination-controls pagination-id='examList' class="pull-right" on-page-change="pageChanged(newPageNumber)" template-url="templates/dirPagination.html"></dir-pagination-controls>
<div dir-paginate="exam in examsList  | itemsPerPage:pageSize:'examList'"                    
      total-items="totalExamItems" 
      pagination-id='examList' 
      current-page="pageNumber" style="display: none">
</div>
```
.continue below
.
.
```
<tr class="listItemsRow" ng-repeat-start="exam in examsList" ng-class="{'archived': exam.disabled==1}">
     
```
.continue below
.
.
` <tr ng-repeat-end ng-class="{'archived': exam.disabled==1}">`

**Comment by javid-duplicity707** [comment] 2025-02-01 04:42
@michaelbromley https://openjs.space/questions/the-value-of-index-remains-constant-for-every-page-that-utilizes-dir-paginate
