### ISSUE TITLE
filter itemsPerPage doesn't support dot notation?

### ISSUE THREAD

**Issue by ffabreti** [michaelbromley/angularUtils#244] opened 2015-10-13 12:22 UTC
when I receive a response from the backend API, I usually wrap it on an object like:
`$scope.response = ajax.data`
where I have something like this:
`{ totalItens : 123,  perPage: 20, page: 3, itens: [ {item1}, {item2},... ] }`
so I can use it on the view like this:

```
<tr ng-if="response.items.length"
            dir-paginate="item in response.items | itemsPerPage: response.perPage
                                  track by item.updated_at"
            total-items="item.totalCount"
            current-page="item.page"
>
```
Problem is that I am getting errors when I use `response.perPage` : 
```
Syntax Error: Token 'as' is at column {2} of the expression [{3}] starting at [{4}].
at Object.dirPaginationCompileFn [as compile] (http://127.0.0.1:3001/assets/dirPagination.js?body=1:65:36)
```
If I use ` itemsPerPage: simpleScopeVar` it works ok.

Adding a breakpoint at line 65 of dirPagination.js, I got this on  Chrome Dev Tools Console:
```
> itemsPerPageFilterRemoved
< "response.items as.perPage"
```

would that be a bug ?

**Comment by michaelbromley** [comment] 2015-10-14 06:47
Hi, are you using the latest version of the script?

**Comment by michaelbromley** [comment] 2015-11-05 09:23
Closing since I believe the problem is fixed in the latest versions. Re-open if this is not the case.

**Closed by michaelbromley** 2015-11-05 09:23 UTC
