### ISSUE TITLE
Tutorial http://angular-meteor.com/tutorials/angular1/search-sort-pagination-and-reactive-vars angularutils:pagination doesn't work

### ISSUE THREAD

**Issue by varelad** [michaelbromley/angularUtils#249] opened 2015-10-18 16:07 UTC
$meteor add angularutils:pagination

While checking for angularutils:pagination@0.9.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

OS. Mac 10.11

If someone can help me.

**Comment by michaelbromley** [comment] 2015-10-18 16:10
Duplicate of https://github.com/michaelbromley/angularUtils/issues/247

**Closed by michaelbromley** 2015-10-18 16:10 UTC
