### ISSUE TITLE
Pagination: {{pageNumber}} not rendering

### ISSUE THREAD

**Issue by snerpton** [michaelbromley/angularUtils#252] opened 2015-10-23 12:21 UTC
Hi Michael,

I have and issue where periodically `{{pageNumbering}}` isn't updated to reflect the actual page numbers in IE11. Furthermore, it never gets updated in IE8. I've tried updating to the most recent version of AngularJS etc., but this doesn't fix the issue.

I believe the 1.3 branch of AngularJS dropped support for IE8, so if I take the last of the 1.2 AngularJS branch do I need to match this with a particular version of dir-pagination, or is it OK to take the most recent version?

Many thanks,
Chris

**Comment by michaelbromley** [comment] 2015-10-29 13:11
Hi,

Can you show me your view & controller code (just the relevant bits)?

I recently updated the build to use AngularJS 1.4 when running the unit tests. That doesn't necessarily mean that it will cause incompatibility with IE8 though. One limitation I do know of is that IE8 doesn't like non-standard HTML tags (which is why you can use both directives as attributes).

**Comment by snerpton** [comment] 2015-11-02 13:34
Hi Michael,

Thanks for getting back to me, and apologies for the delay in replying – I was at a conference.

As you hinted at, I'm using the attribute rather than directive method due to IE8 limitations.

The relevant part of my view is:

```html
<div data-ng-app="onlineSystemsApp">
    <div data-ng-controller="onlineSystemsCtrl" id="onlineSystemsCtrl" class="row">              
            <div class="tools-search-controls input-group col-sm-6">
            <input type="text" placeholder="Search" class="editable-input form-control"  data-ng-model="Title" />
        </div>
        <table class="table table-bordered table-hover table-condensed table-online-systems">
            <tr>
                <th class="col-name"><a href="" data-ng-click="predicate = 'Title'; reverse=!reverse">System Name</a></th>
                <th class="col-desc"><a href="" data-ng-click="predicate = 'Description'; reverse=!reverse">Description</a></th>
                <th class="col-category"><a href="" data-ng-click="predicate = 'Category'; reverse=!reverse">Category</a></th>

            </tr>

            <tr dir-paginate="item in onlineSystemsData | orderBy:predicate:reverse | filter:Title | itemsPerPage:20">

                <td class="col-name">
                    <div class="table-inner">
                        <a target="_blank" href="{{item.Link}}">{{item.Title}}</a>
                    </div>
                </td>
                <td class="col-desc">
                    <div class="table-inner">
                        {{item.Description}}
                    </div>
                </td>
                <td class="col-category">
                    <div class="table-inner">
                        {{item.Category}}
                    </div>
                </td>

            </tr>

        </table>       
           
        <div dir-pagination-controls boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url=""></div>
    </div>

</div>
```

and my controller:

```javascript
onlineSystemsApp.controller('onlineSystemsCtrl', function ($scope, $location, $http) {

    //Get initial list of items for search results list
    $scope.onlineSystemsData = [];
    $http.get('/Umbraco/Api/OnlineSystemsApi/GetAll')
        .success(function (data) {
            $scope.onlineSystemsData = data;
        }).error(function (data) {
            $scope.data = data || "Request failed";
        });

});
```

I don't think these are relevant, but for completeness, this is my app:

```javascript
var onlineSystemsApp = angular.module('onlineSystemsApp', ['onlineSystemsServices', 'angularUtils.directives.dirPagination']);

onlineSystemsApp.filter('startFrom', function () {
    return function (input, start) {
        start = +start; 
        if (typeof input != 'undefined') {
            return input.slice(start);
        }
    }
});
```

and service:

```javascript
var onlineSystemsServices = angular.module('onlineSystemsServices', ['ngResource']);

onlineSystemsApp.factory('onlineSystemsServices', function ($resource) {
    var resource = $resource('/Umbraco/Api/OnlineSystemsApi/Search');
    return {
        search: function (searchText) {
            return resource.query(searchText);
        },
    };
});
```


I'm including the files in the following order:

- `angular-1.2.27/angular.min.js`
- `angular-1.2.27/angular-resource.min.js`
- `online-services.app.js`
- `online-services.services.js`
- `online-services.ctrl.js`
- `dirPagination.js`

**Comment by michaelbromley** [comment] 2015-11-05 09:11
Hi,

Thanks for the code - nothing obvious is amiss there. Couple of specifics to help me think with this:

1. This "periodically" happens in IE11 - how often? And is there a particular sequence of actions that brings it about? E.g. changing the order, changing the filter, etc?
2. To be clear what is meant by "{{pageNumbering}} isn't updated to reflect the actual page numbers " - do you mean that, say, if there are 100 items with 20 per page, therefore there should be 5 page links generated by `dir-pagination-controls`, but there are more or less than 5? Or do you mean the currently-active page is incorrect? Or something else? Since I have no way to reproduce this (the [demo](http://plnkr.co/edit/Wtkv71LIqUR4OhzhgpqL?p=preview) seems to work fine for me in IE11. Plunker dies in IE8 so I have not tested that just now), then a most precise description is helpful.

**Comment by ishammael** [comment] 2015-11-06 11:33
Hello,
I could recreate this every time in ie11, although your demo worksjust fine.
My crude fix: <a href="" ng-click="setCurrent(pageNumber)"><span style="display: none">PN:</span>{{pageNumber}}</a>
Adding something into the link (i hide that span because i dont want it displayed there) renders {{pageNumber}} in ie11.

Hope this helps a little bit in finding the cause of it!

**Comment by michaelbromley** [comment] 2016-03-01 09:47
@ishammael thanks for the input. Gonna close this now, please re-open if this is still an issue.

**Closed by michaelbromley** 2016-03-01 09:47 UTC
