### ISSUE TITLE
Getting object count after filter.

### ISSUE THREAD

**Issue by PringPring** [michaelbromley/angularUtils#406] opened 2016-10-03 10:42 UTC
After filtering the records how to get the current object count on the current controller.
[stackoverflow question](https://stackoverflow.com/questions/39825212/how-to-get-array-count-of-filtered-result-on-dir-pagination)

**Comment by Aides359** [comment] 2016-11-10 11:42
You can access the filtered result to a new variable with 

    <li dir-paginate="meal in filteredMeals = (meals | filter:q) 
         | itemsPerPage: pageSize" current-page="currentPage">

and then access `filteredMeals.length`.

**Comment by Aides359** [comment] 2016-11-11 10:17
also duplicate of #328

**Comment by michaelbromley** [comment] 2016-11-11 13:31
@Aides359 exactly. Thanks for helping out 👍

**Closed by michaelbromley** 2016-11-11 13:31 UTC
